## Problem Statement 1:  

Write  a  function  so  that  the  columns  of  the  output  matrix  are  powers  of  the  input vector.   
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing  is  False, 
the  i-th output column  is the input vector raised element-wise to the power of N - i - 1.   

            HINT:  Such  a  matrix with a geometric  progression  in each  row  is  named for Alexandre-  
            Theophile Vandermonde.    
            
            Note: Solution submitted via github must contain all the detailed steps. 

In [6]:
# Wihtout usiing in built function
import numpy as np                                                          # importing the numpy
inpArr=input("Enter the input vector with comma separated ")                 # input vector
inpArr=inpArr.split(',')
inpArrnew=[int(item) for item in inpArr]
                                                  
n=input("Enter the n vlaue(integer) or enter None ")                         # geometric progression n value 
if(n=="None"):                                                               # checking the N value
    itr=range(len(inpArrnew)) 
    n=len(inpArrnew)
else:
    itr=range(int(n)) 
    n=int(n)
itr=[item for item in itr]
rev=itr[::-1]
outputFal=np.asarray([inp**itrval for itrval in rev for inp in inpArrnew])   # Generating the values as per Geometric progression
outputFal=outputFal.reshape(n,len(inpArrnew))                                # reshaping the array
print("\nVandermonde Matrix in increasing order is False")
outFal=outputFal.transpose()
print(outFal)                                                               # output array

outputVal=np.asarray([inp**itrval for itrval in itr for inp in inpArrnew])   # Generating the values as per Geometric progression
outputVal=outputVal.reshape(n,len(inpArrnew))                                # reshaping the array
print("\nVandermonde Matrix in increasing order  is True")
outval=outputVal.transpose()
print(outval)                                                               # output array

Enter the input vector with comma separated 1,2,3,4,5
Enter the n vlaue(integer) or enter None None

Vandermonde Matrix in increasing order is False
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]

Vandermonde Matrix in increasing order  is True
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [7]:
#Function using numpy.vander() function
import numpy as np
def vanderMatrix(inputVec,N):
    inputArray = np.array(inputVec)
    if(N!=None):                                                   # when N is defined  
        outputArray = np.vander(inputArray, N, increasing=False)   # creating vander matrix when N is defined & Increasing =false
        print('Vandermonde Matrix when increasing is False ')
        print(outputArray)                                         # Displaying the output when increasing order is False
        print('\nVandermonde Matrix when increasing is True ')     
        outputArray = np.vander(inputArray,N,increasing=True)      # creating vander matrix when N is defined & Increasing =true
        print(outputArray)
    else:                                            
        # N is undefined, so Square matrix is created based upon inputvector length
        outputArray = np.vander(inputArray, N, increasing=False) # creating vander matrix when N is undefined & Increasing=false
        print('Vandermonde Matrix when increasing order is False ')
        print(outputArray)
        # increasing order is True
        outputArray = np.vander(inputArray,N,increasing=True)    # creating vander matrix when N is undefined & Increasing =true
        print('Vandermonde Matrix when increasing order is True ')
        print(np.flip(outputArray,axis=1)) 
        
vanderMatrix([1,2,3,4,5],None)         # With N = None

Vandermonde Matrix when increasing order is False 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Vandermonde Matrix when increasing order is True 
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [8]:
vanderMatrix([1,2,3,4,5],4)             # With N=4

Vandermonde Matrix when increasing is False 
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

Vandermonde Matrix when increasing is True 
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
